project:
  type: book
  output-dir: docs

book:
  title: "microclim"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_data.qmd
      chapters:
      - 11_microclimate.qmd
      - 12_macroclimate.qmd
      - 13_guyaflux.qmd
      - 14_vegetation.qmd
      - 15_topography.qmd
      - 16_pedology.qmd
    - part: 20_analyses.qmd
      chapters:
      - 21_macroclimate.qmd
      - 22_microclimate.qmd
  appendices:
    - 96_literature.qmd
    - 97_meeting.qmd
    - 98_contributing.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
